### ISSUE TITLE
[Suggestion] Enhanced Celestials compatibility

### ISSUE THREAD

**Issue by Neko2n** [Sindarin27/farsighted-mobs-forge#1]
Could we get Enhanced Celestials compatibility for configuring mob view distances based on lunar events? Ie. Zombies having 100 block detection range during blood moons, causing a zombie apocalypse horde effect.

**Comment by Sindarin27** [comment]
Sorry for the very late reply. This is something I would like to add in the future, but requires a full rewrite of the configuration system. Planned but not on short term.

**Comment by Sindarin27** [comment]
Moved to https://github.com/Sindarin27/farsighted-mobs/issues/12
