### ISSUE TITLE
[Suggestion] Modify mob's ranged attacks to match their increased detection range.

### ISSUE THREAD

**Issue by zachsai** [Sindarin27/farsighted-mobs-forge#2]
![image](https://user-images.githubusercontent.com/63996164/159136352-832b7ca6-192f-4043-9d29-cf080826f9d6.png)

**Comment by Sindarin27** [comment]
Planned but not on short term. Possible ways to implement this:
- Giving ranged mobs a better aim
- Preventing ranged mobs from firing projectiles when they're outside of a certain (configurable) maximum range

**Comment by Sindarin27** [comment]
Abandoned, similar issue over at https://github.com/Sindarin27/farsighted-mobs/issues/7
