### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Arch23-tech** [Sindarin27/farsighted-mobs-forge#9]
I just need to know if the mod allows you to do the opposite...

I mean reducing the range instead of increasing in the config.?

Because in the description it only talks about how the increases range of detection....

**Comment by Sindarin27** [comment]
Currently only through individual overrides. `minHostileFollowRange` sets the minimum follow range of hostile mobs (as the name implies) but `mobFollowRangeOverrides` actually *overrides* the follow range of the mob regardless of whether the original value was higher or lower.
